version: "3.9"

services:

  flask_db:
    container_name: flask_db
    image: postgres:12
    ports: 
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=userpg
      - POSTGRES_PASSWORD=Puchy5531
      - POSTGRES_DB=DirectoryAPP
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 10s

  flask_app:
    container_name: flask_app
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql://userpg:Puchy5531@flask_db:5432/DirectoryAPP
    depends_on:
      flask_db: 
            condition: service_healthy
            restart: true
    
volumes:
  pgdata: {}