kind: Template
apiVersion: v1
metadata:
  name: Practica2
  annotations:
    description: >-
      Platilla de despliegue
    tags: "flask,python"

parameters:
  - name: APP_NAME
    description: Nombre de applicaci贸n (Prefijo de todos los objetos).
    required: true
  
  - name: DB_NAME
    description: Nombre de la base de datos.
    value: mydb

  - name: DB_USR
    description: Nombre de usario para conexi贸n a la base de datos.
    value: myuser

  - name: DB_PWD
    description: Password de usuario para conexi贸n a la base de datos.
    required: true

  - name: DOMAIN_NAME
    description: Nombre de dominio para la publicaci贸n de la ruta.
    required: true

  - name: PROJECT_NAME
    description: Nombre de projecto
    required: true
    

labels:
  app: "${APP_NAME}"

objects:

  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${APP_NAME}-keys"
    type: Opaque
    stringData:
      db_pwd: '${DB_PWD}'
      db_usr: '${DB_USR}'
      db_name: '${DB_NAME}'
      db_url: 'postgresql://${DB_USR}:${DB_PWD}@${APP_NAME}-flask-db.${PROJECT_NAME}.svc:5432/${DB_NAME}'

  - kind: Service
    apiVersion: v1
    metadata:
      name: "${APP_NAME}-flask-app"
    spec:
      ports:
        - name: flask-app
          port: 8000
          targetPort: 8000
      selector:
        name: "${APP_NAME}-flask-app"
    
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${APP_NAME}-flask-app
      name: ${APP_NAME}-flask-app
    spec:
      host: ${DOMAIN_NAME}
      port:
        targetPort: flask-app
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-flask-app
        weight: 100
      wildcardPolicy: None
  
  - apiVersion: v1
    kind: Service
    metadata:
      name: '${APP_NAME}-flask-db'
    spec:
      type: ClusterIP
      ports:
        - name: postgresql
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        name: '${APP_NAME}-flask-db'

  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: '${APP_NAME}-flask-db'
    spec:
      replicas: 1
      selector:
        name: ${APP_NAME}-flask-db
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: "${APP_NAME}-flask-db"
        spec:
          containers:
            - env:
              - name: POSTGRESQL_USER
                valueFrom:
                  secretKeyRef:
                    name: "${APP_NAME}-keys"
                    key: db_usr
              - name: POSTGRESQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: "${APP_NAME}-keys"
                    key: db_pwd
              - name: POSTGRESQL_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: "${APP_NAME}-keys"
                    key: db_name
              image: ' '
              imagePullPolicy: Always
              livenessProbe:
                exec:
                  command:
                    - /usr/libexec/check-container
                    - '--live'
                failureThreshold: 3
                initialDelaySeconds: 120
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 10
              name: postgresql
              ports:
                - containerPort: 5432
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - /usr/libexec/check-container
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  memory: "1G"
                requests:
                  memory: "1G"
              volumeMounts:
                - mountPath: /var/lib/pgsql/data
                  name: postgresql-data
                  subPath: pgsql-data
          restartPolicy: Always
          securityContext:
            supplementalGroups:
              - 5688
          volumes:
            - name: postgresql-data
              persistentVolumeClaim:
                claimName: "data"
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - postgresql
            from:
              kind: ImageStreamTag
              name: 'postgresql:12'
              namespace: 'openshift'
            lastTriggeredImage: ''
          type: ImageChange
        - type: ConfigChange
  
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: "${APP_NAME}-flask-app"
    spec:
      replicas: 1
      selector:
        name: "${APP_NAME}-flask-app"
      template:
        metadata:
          labels:
            app: "${APP_NAME}-flask-app"
            name: "${APP_NAME}-flask-app"
        spec:
          containers:
            - image: 'jcliu08/practica2'
              imagePullPolicy: Always
              name: flask-app
              env:
                - name: DB_URL
                  valueFrom:
                    secretKeyRef:
                      name: "${APP_NAME}-keys"
                      key: db_url
              ports:
                - containerPort: 8000
                  protocol: TCP
              resources:
                limits:
                  memory: "256M"
                requests:
                  memory: "256M"
          restartPolicy: Always
      test: false
