version: '3.9'

services:

  postgres-db:
    image: 'postgres:15.0-alpine'
    restart: always
    environment:
      POSTGRES_DB: DirectoryAPP
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Puchy5531
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      bash -c "
      dockerize -wait tcp://localhost:5432 -timeout 30s &&
      psql -U postgres -d DirectoryAPP -c 'CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";' &&
      dart run conduit db upgrade
      "
    networks:
      - my_project_net
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 30s

  my_project:
    build: .
    restart: always
    ports:
      - 8888:8000
    environment:
       DATABASE_URL: postgres://postgres:Puchy5531@localhost:5432/DirectoryAPP
    networks:
      - my_project_net
    depends_on:
      postgres-db:
        condition: service_healthy
        restart: true

volumes:
  postgres_data:
  
networks:
  my_project_net: